/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SRA;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Willy1412
 */
public class StudentServiceApplication extends javax.swing.JFrame {

    ArrayList<Student> student = new ArrayList<>();
    ArrayList<Course> courseMajor = new ArrayList<>();
    ArrayList<Course> enrollClass = new ArrayList<>();
    ArrayList<Room> rooms = new ArrayList<>();
    ArrayList<Room> rooms2 = new ArrayList<>();
    DefaultListModel dlm = new DefaultListModel();
    DefaultListModel dlm1 = new DefaultListModel();
    DefaultListModel dlm2 = new DefaultListModel();
    DefaultListModel dlm3 = new DefaultListModel();
    
    /**
     * Creates new form StudentServiceApplication
     */
    public StudentServiceApplication() {
        initComponents();
        
        courseMajor.add(new Course("Computer Science (CS)"));
        courseMajor.add(new Course("Information System (IS)"));
        courseMajor.add(new Course("Graphic Design (GD)"));
        
        rooms.add(new Room("FX601", false));
        rooms.add(new Room("FX602", false));
        rooms.add(new Room("FX603", false));
        rooms.add(new Room("FX604", false));
        
        rooms2.add(new Room("JWC201", false));
        rooms2.add(new Room("JWC202", false));
        rooms2.add(new Room("JWC203", false));
        rooms2.add(new Room("JWC204", false));
        
        showMajorList();
        showClassList();
        showRoom1List();
        showRoom2List();
    }
    
    public void showMajorList(){
        dlm = new DefaultListModel();
        
        for(int i=0 ; i<courseMajor.size() ; i++){
            dlm.addElement(courseMajor.get(i).getCourseMajor());
        }
        majorList.setModel(dlm);
    }
    
    public void showClassList(){

        dlm1 = new DefaultListModel();
        
        for(int i=0 ; i<enrollClass.size() ; i++){
            dlm1.addElement(enrollClass.get(i).getCourseCode());
        }
        classList.setModel(dlm1);
    }
    
    public void showRoom1List(){
        
        dlm2 = new DefaultListModel();
        
        for(int i=0 ; i<rooms.size() ; i++){
            dlm2.addElement(rooms.get(i).getRoomName());
        }
        roomList.setModel(dlm2);
    }
    
    public void showRoom2List(){
        
        dlm3 = new DefaultListModel();
        
        for(int i=0 ; i<rooms2.size() ; i++){
            dlm3.addElement(rooms2.get(i).getRoomName());
        }
        roomList2.setModel(dlm3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        courseCodeField = new javax.swing.JTextField();
        courseNameField = new javax.swing.JTextField();
        courseQuotaField = new javax.swing.JTextField();
        createClassButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        courseMajorField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        majorList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        classList = new javax.swing.JList<>();
        refreshButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        enrollButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        classNameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        classQuotaField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomList = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        roomList2 = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        bookButton2 = new javax.swing.JButton();
        refreshRoomButton = new javax.swing.JButton();
        refreshRoom2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        studentIdRoom = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Student Service Application");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add a Class"));

        jLabel2.setText("Course Code:");

        jLabel3.setText("Course Name:");

        jLabel4.setText("Course Quota:");

        createClassButton.setText("Create Class");
        createClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClassButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Major:");

        courseMajorField.setEditable(false);
        courseMajorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseMajorFieldActionPerformed(evt);
            }
        });

        majorList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        majorList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                majorListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(majorList);

        jLabel6.setText("List of Majors");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseQuotaField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(courseCodeField)
                            .addComponent(courseNameField)
                            .addComponent(courseMajorField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(createClassButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(courseCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(courseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(courseQuotaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createClassButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Enroll a Student"));

        jLabel7.setText("Available Class ID");

        classList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        classList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(classList);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Student ID:");

        studentIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdFieldActionPerformed(evt);
            }
        });

        enrollButton.setText("Enroll");
        enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Class Name:");

        classNameField.setEditable(false);
        classNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classNameFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Class Quota:");

        classQuotaField.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(refreshButton))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(enrollButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentIdField)
                                    .addComponent(classQuotaField)
                                    .addComponent(classNameField)))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(classNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(classQuotaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enrollButton))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Book a Room"));

        roomList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        roomList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomListMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(roomList);

        jLabel11.setText("Available Room for Projects/Research");

        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        roomList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        roomList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomList2MouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(roomList2);

        jLabel12.setText("Available Room for Group Study");

        bookButton2.setText("Book");
        bookButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButton2ActionPerformed(evt);
            }
        });

        refreshRoomButton.setText("Refresh");
        refreshRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRoomButtonActionPerformed(evt);
            }
        });

        refreshRoom2.setText("Refresh");
        refreshRoom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRoom2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Student ID:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(bookButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookButton2)
                .addGap(45, 45, 45))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(refreshRoomButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshRoom2)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentIdRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(studentIdRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookButton)
                    .addComponent(bookButton2))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshRoomButton)
                    .addComponent(refreshRoom2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClassButtonActionPerformed
        // TODO add your handling code here:
        String major = courseMajorField.getText();
        String code = courseCodeField.getText();
        String name = courseNameField.getText();
        String quota = courseQuotaField.getText();
        
        if(major.equals("Computer Science (CS)")){
            enrollClass.add(new Course(code, name, quota));
            JOptionPane.showMessageDialog(this, "Added Computer Science Class (Code = " + code + ", Name = "+ name + ", Quota = "+ quota + ")");
        }else if(major.equals("Information System (IS)")){
            enrollClass.add(new Course(code, name, quota));
            JOptionPane.showMessageDialog(this, "Added Information System Class (Code = " + code + ", Name = "+ name + ", Quota = "+ quota + ")");
        }else if(major.equals("Graphic Design (GD)")){
            enrollClass.add(new Course(code, name, quota));
            JOptionPane.showMessageDialog(this, "Added Graphic Design Class (Code = " + code + ", Name = "+ name + ", Quota = "+ quota + ")");
        }else{
            JOptionPane.showMessageDialog(this, "No such Major");
        }
    }//GEN-LAST:event_createClassButtonActionPerformed

    private void majorListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majorListMouseClicked
        // TODO add your handling code here:
        for(int i=0 ; i<courseMajor.size() ; i++){
            if(courseMajor.get(i).getCourseMajor().equals(majorList.getSelectedValue())){
                courseMajorField.setText(courseMajor.get(i).getCourseMajor());
            }
        }
    }//GEN-LAST:event_majorListMouseClicked

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        dlm1 = new DefaultListModel();
        
        for(int i=0 ; i<enrollClass.size() ; i++){
            dlm1.addElement(enrollClass.get(i).getCourseCode());
            // + " - " + enrollClass.get(i).getCourseName() + " - " + enrollClass.get(i).getCourseQuota()
        }
        classList.setModel(dlm1);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void courseMajorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseMajorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseMajorFieldActionPerformed

    private void enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollButtonActionPerformed
        // TODO add your handling code here:
        String studentId = studentIdField.getText();
        
        student.add(new Student(studentId));
        
        for(int i = 0; i < enrollClass.size(); i++){
            JOptionPane.showMessageDialog(this, studentId + " has been enrolled into the " + enrollClass.get(i).getCourseName() + " class");
        }
        
    }//GEN-LAST:event_enrollButtonActionPerformed

    private void classListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classListMouseClicked
        // TODO add your handling code here:
        for(int i=0 ; i<enrollClass.size() ; i++){
            if(enrollClass.get(i).getCourseCode().equals(classList.getSelectedValue())){
                classNameField.setText(enrollClass.get(i).getCourseName());
                classQuotaField.setText(enrollClass.get(i).getCourseQuota());
            }
        }
    }//GEN-LAST:event_classListMouseClicked

    private void classNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classNameFieldActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        String sid = studentIdRoom.getText();
        int index = roomList.getSelectedIndex();

        rooms.get(index).setRoomBooked(true);
        
        JOptionPane.showMessageDialog(this, sid + " booked a room for Projects/Research!");
    }//GEN-LAST:event_bookButtonActionPerformed

    private void roomListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomListMouseEntered
        // TODO add your handling code here:
        roomList2.clearSelection();
    }//GEN-LAST:event_roomListMouseEntered

    private void roomList2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomList2MouseEntered
        // TODO add your handling code here:
        roomList.clearSelection();
    }//GEN-LAST:event_roomList2MouseEntered

    private void bookButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButton2ActionPerformed
        // TODO add your handling code here:
        String sid = studentIdRoom.getText();
        int index = roomList2.getSelectedIndex();

        rooms2.get(index).setRoomBooked(true);
        
        JOptionPane.showMessageDialog(this, sid + " booked a room for Group Study!");
    }//GEN-LAST:event_bookButton2ActionPerformed

    private void refreshRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRoomButtonActionPerformed
        // TODO add your handling code here:
        dlm2.removeAllElements();
        for (int j=0 ; j<rooms.size() ; j++){
            if(rooms.get(j).roomBooked == false){
                dlm2.addElement(rooms.get(j).roomName);
            }
        }
        roomList.setModel(dlm2);
    }//GEN-LAST:event_refreshRoomButtonActionPerformed

    private void refreshRoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRoom2ActionPerformed
        // TODO add your handling code here:
        dlm3.removeAllElements();
        for (int j=0 ; j<rooms.size() ; j++){
            if(rooms2.get(j).roomBooked == false){
                dlm3.addElement(rooms2.get(j).roomName);
            }
        }
        roomList2.setModel(dlm3);

    }//GEN-LAST:event_refreshRoom2ActionPerformed

    private void studentIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentServiceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentServiceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentServiceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentServiceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentServiceApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookButton;
    private javax.swing.JButton bookButton2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<String> classList;
    private javax.swing.JTextField classNameField;
    private javax.swing.JTextField classQuotaField;
    private javax.swing.JTextField courseCodeField;
    private javax.swing.JTextField courseMajorField;
    private javax.swing.JTextField courseNameField;
    private javax.swing.JTextField courseQuotaField;
    private javax.swing.JButton createClassButton;
    private javax.swing.JButton enrollButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> majorList;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton refreshRoom2;
    private javax.swing.JButton refreshRoomButton;
    private javax.swing.JList<String> roomList;
    private javax.swing.JList<String> roomList2;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JTextField studentIdRoom;
    // End of variables declaration//GEN-END:variables
}
